name: Set up dependencies
description: Set up Node.js and install package dependencies.

runs:
  using: composite

  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      id: cache-packages
      with:
        cache: npm
        node-version: 16

    - name: Cache NPM dependencies
      uses: actions/cache@v3
      id: cache-primes
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash

